# Generated by Django 3.1.5 on 2021-05-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniMart', '0002_auto_20210518_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_name', models.CharField(choices=[('outdoor', 'outdoor'), ('Indoor', 'Indoor'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MiniMart.tags'),
        ),
    ]
