# Generated by Django 3.1.5 on 2021-05-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniMart', '0004_auto_20210519_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Tag_name',
            new_name='name',
        ),
    ]
