# Generated by Django 3.1.5 on 2021-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniMart', '0005_auto_20210519_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Snack', 'Snack'), ('FastFood', 'FastFood'), ('Drink', 'Drink'), ('Games', 'Games')], max_length=200, null=True),
        ),
    ]
