# Generated by Django 3.1.5 on 2021-05-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniMart', '0007_auto_20210519_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stats',
            new_name='status',
        ),
    ]
