# Generated by Django 3.1.5 on 2021-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniMart', '0016_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to=''),
        ),
    ]
